### ISSUE TITLE
Issue with crabs db_download with mitofish

### ISSUE THREAD

**Issue by laninsky** [gjeunen/reference_database_creator#14]
Kia ora GJ mā, ngā mihi o te tau hou Pākehā! @bigdog-836 and I are trying to download the mitofish database using the crabs conda installation (as far as I know Docker does not play well on the NeSI infrastructure). We are getting the following error:
```
 crabs db_download --source mitofish --output mitofish.fasta --keep_original yes

downloading sequences from the MitoFish database
Traceback (most recent call last):
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 1372, in <module>
    main()
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 1369, in main
    args.func(args)
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 96, in db_download
    dl_file = mitofish_download(url)
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/lib/python3.6/site-packages/function/module_db_download.py", line 139, in mitofish_download
    os.remove('complete_partial_mitogenomes.zip')
FileNotFoundError: [Errno 2] No such file or directory: 'complete_partial_mitogenomes.zip'
```
Thanks for the help!

**Comment by laninsky** [comment]
Cool, thanks GJ. We'll start from scratch with the github version tomorrow.
