### ISSUE TITLE
in_silico PCR error (missing init_trimmed.fasta)

### ISSUE THREAD

**Issue by mikeallen-eco** [gjeunen/reference_database_creator#22]
Hello,

I installed CRABS in linux via cloning the GitHub. I successfully downloaded COI and 16S sequences for Arthropods from ncbi. The following insilco_pcr command produced an error related to cut adapt:

crabs insilico_pcr --input ncbi_coi_16s_may23.fasta --output final_ncbi_coi_16s_may23.C.fasta --fwd TGCAAAGGTAGCATAATMATTAG --rev TCCATAGGGTCTTCTCGTC --error 4.5

Should I use a different setting for the --error argument? Thanks. The error is:

cutadapt: error: The maximum error rate must be between 0 and 1.

Traceback (most recent call last):
  File "/projects/f_deenr_1/mcallen/reference_database_creator/crabs", line 1428, in <module>
    main()
  File "/projects/f_deenr_1/mcallen/reference_database_creator/crabs", line 1425, in main
    args.func(args)
  File "/projects/f_deenr_1/mcallen/reference_database_creator/crabs", line 267, in insilico_pcr
    with tqdm(total = os.path.getsize(TRIMMED_INIT)) as pbar:
  File "/home/mcallen/miniconda3/envs/py37/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'init_trimmed.fasta'

**Comment by mikeallen-eco** [comment]
This was solved by ensuring that the proper version of cutadapt was installed (version 1.8 updated to 4.4).
