### ISSUE TITLE
problem with the "--export" command

### ISSUE THREAD

**Issue by DrPaulFrank** [gjeunen/reference_database_creator#71]
Hi there,
I am working with the manually installed Crabs, and everything is working well. However, when I call the "--export" function I get an error, independent on the python version I use.  A variation of the error message looks like:

Traceback (most recent call last):
  File "/data/paolo/software/reference_database_creator/crabs", line 847, in <module>
    crabs()
  File "/bioinf/miniforge/lib/python3.10/site-packages/click-8.1.7-py3.10.egg/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/bioinf/miniforge/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/bioinf/miniforge/lib/python3.10/site-packages/click-8.1.7-py3.10.egg/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bioinf/miniforge/lib/python3.10/site-packages/click-8.1.7-py3.10.egg/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/paolo/software/reference_database_creator/crabs", line 823, in crabs
    console.print(f"[cyan]|            Function[/] | Export CRABS database to {export_format_.upper()} format")
AttributeError: 'NoneType' object has no attribute 'upper'

Thanks for your help!
Paolo

**Comment by gjeunen** [comment]
Hello @DrPaulFrank,

Could you please provide the line of code you execute when receiving this error. `AttributeError: 'NoneType' object has no attribute 'upper'` indicates that a parameter is missing, but it is hard to tell without the actual command.

Thanks and best wishes,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @DrPaulFrank,

I assume this has been sorted now, but please reopen this issue if your problem persists.

Best wishes,
Gert-Jan
